export const config = {
  PYLON_API_URI: process.env.NEXT_PUBLIC_PYLON_API_URI,
  WALLETCONNECT_PID: process.env.NEXT_PUBLIC_WALLETCONNECT_PID,
  PYLON_PASSWORD: process.env.NEXT_PUBLIC_PYLON_PASSWORD,
  ALCHEMY_API_KEY: process.env.NEXT_PUBLIC_ALCHEMY_API_KEY,
  CHAIN_ID: process.env.NEXT_PUBLIC_CHAIN_ID
}
